(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "find-file-in-project")
(depends-on "flymake-cursor")
(depends-on "flymake-python-pyflakes")
(depends-on "hlinum")
(depends-on "jedi")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "s")
(depends-on "shut-up")
(depends-on "yaml-mode")